# Generated by Django 3.1.2 on 2020-12-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='pet_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
